/* eslint-disable prettier/prettier */
export const categoriesData = [
  "Software Engineering",
  "Web Development",
  "Cybersecurity",
  "DevOps",
  "Machine Learning",
  "Blockchain",
  "UI/UX Design",
  "Database Management",
  "Data Science",
  "Software Testing",
  "System Design",
  "Internet of Things (IoT)",
  "Security Practices",
  "Frontend Development",
  "Backend Development",
  "Fullstack Development",
  "Mobile App Development",
  "Cloud Computing",
  "Agile Methodology",
  "Project Management",
  "Performance Optimization",
  "Containerization",
  "API Management",
  "Distributed Systems",
];
